project:
  type: website
  output-dir: docs
  
website:
  title: "CS-5805-Machine-Learning-Blogs"
  repo-url: https://github.com/rahulsatoskar/CS-5805-Machine-Learning-Blogs.git
  repo-actions: [source]
  navbar:
    right:
      - href: index.qmd
        text: Home
      - about.qmd
      - icon: github
        href: https://github.com/rahulsatoskar
      - icon: github
        href: https://github.com/rahulsatoskar/CS-5805-Machine-Learning-Blogs.git
      - text: "Link to Github Repository"

format:
  html:
    theme:
      light: litera
      dark: darkly
    css: styles.css
    highlight-style: espresso
    code-tools: true
editor: visual
